language: c

os:
  - linux

sudo: required

install:
   - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
   - sudo apt-get --yes --force-yes update -qq
   - sudo apt-get install --yes libgdal-dev
   - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf'
#   - sudo ldconfig

script:
  - make
  - sudo make install