language: c

sudo: required

install:
   - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
   - sudo apt-get --yes --force-yes update -qq
   - sudo apt-get install --yes libgdal-dev
   - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf'
   - sudo sh -c 'echo "/usr/local/include" > /etc/ld.so.conf.d/local.conf'
   - sudo sh -c 'echo "/usr/include/gdal" >> /etc/ld.so.conf.d/local.conf'
   - mkdir sml ezgdal
   - wget http://pawel.netzel.pl/gitlist/index.php/ezGDAL/tarball/master -O ezgdal.tar
   - tar -xvf ezgdal.tar -C ezgdal
   - pushd ezgdal && make && sudo make install && popd
   - wget http://pawel.netzel.pl/gitlist/index.php/SML/tarball/master -O sml.tar
   - tar -xvf sml.tar -C sml
   - pushd sml && make && sudo make install && popd
   - sudo ldconfig

script:
  - make
  - sudo make install