language: c

sudo: required

before_install:
   - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
   - sudo apt-get --yes --force-yes update -qq
   - sudo apt-get install --yes libgdal-dev
   - mkdir sml ezgdal
   - wget http://pawel.netzel.pl/gitlist/index.php/SML/tarball/master -O sml.tar
   - tar -xvf sml.tar -C sml
   - cd sml && make && sudo make install
   - wget http://pawel.netzel.pl/gitlist/index.php/ezGDAL/tarball/master -O ezgdal.tar
   - tar -xvf ezgdal.tar -C ezgdal
   - cd ezgdal && make && sudo make install
   - sudo ldconfig

script:
  - make
  - sudo make install