language: c

os:
  - linux
  - osx

sudo: required

before_install:

  - if [[ $TRAVIS_OS_NAME == linux ]]; then
   sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes;
   sudo apt-get --yes --force-yes update -qq;
   sudo apt-get install --yes libgdal-dev;
   sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf';
    fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm; fi

script:
  - make
  - sudo make install