language: c

sudo: required

install:
   - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
   - sudo apt-get --yes --force-yes update -qq
   - sudo apt-get install --yes libgdal-dev
   - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf'
   - wget http://sil.uc.edu/cms/data/uploads/software_data/GPAT2/ezGDAL.tar.gz
   - tar zxvf ezGDAL.tar.gz
   - pushd ezGDAL && make && sudo make install && popd
   - wget http://sil.uc.edu/cms/data/uploads/software_data/GPAT2/SML.tar.gz
   - tar zxvf SML.tar.gz
   - pushd SML && make && sudo make install && popd
   - sudo ldconfig

script:
  - make
  - sudo make install